### ISSUE TITLE
crond do not deal with changes in crontab under certain circumstances

### ISSUE THREAD

**Issue by HangYu-T** [cronie-crond/cronie#51]
the timestamps at the following codeline is one-second precision.
https://github.com/cronie-crond/cronie/blob/22ae88868f48090e2a5ad4b9bb165581df91511f/src/database.c#L250

so , what if the crontab is modefied twice in one second and the timestamps is just the same。

in the following case , excute the step 2 ,4 in the same one second to make timestamps is the same .the changes of step 4 will be lost ,because of the timestamps has not changed, 
1.start crond ( crond begin to start load database. )
2.modifiy crontab
3. crond load database done
4. modify the crontab again

**Comment by t8m** [comment]
I do not think this can happen. Please note that in the situation where the 2. and 3. happen in the same second the mtime in this situation is actually _now_-1.  But then when you modify the crontab again in the same second another load will happen after a minute and the mtime in this load will be '_now_ from the time of the modification' where the u->mtime will be _now_ from the time of the modification -1. So the file will be loaded in the next load.
Unless you have a script that can reproduce it with current cronie.
Please note that the race condition was real but it was fixed with e91b6ebbef989cd167607e44f99424a3c0a8f24d.

**Comment by t8m** [comment]
Also I want to add that we really do not care about possible races of this kind when system clock (in UTC) can go backwards.

**Comment by HangYu-T** [comment]
thanks for your reply

code of the cronie on my machine is too old.
so i have  confused why don't use nanosecond when comparing the timestamps.
  
but i have update the cronie on my machine with centos 7.5. and test this case 
the fix works well .
https://github.com/cronie-crond/cronie/commit/e91b6ebbef989cd167607e44f99424a3c0a8f24d

thanks a lot again. I'm going to close this issue.
